name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Automated Tests
    types:
      - completed

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  check-changesets:
    name: Check Changesets
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.check-changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Check Changeset Status
        run: |
          if npx changesets status; then
            echo "hasChangesets=true" >> "$GITHUB_OUTPUT"
          else
            echo "hasChangesets=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check-changesets
    if: ${{ needs.check-changesets.outputs.hasChangesets != 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to NPM
        run: npm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
